start_map: level1
maps:
     - name: level1
       north_angle: 0.0
     - name: level2
       north_angle: 0.0

wormholes:
     - name: elevator1 # for Gazebo simulation, this should be same as the spawn model name
       type: elevator_blast
       radius: 0.2
       locations:
            - map: level1 
              position: [8.87, 27.6] # dump coordinates
              waiting_point: [8.59 31.37 -1.598] # x, y, yaw
              floor: 0 
              height: 0.0 # not used, but might be useful in the future to calculate the cost of using the elevator
            - map: level2
              position: [8.87, 27.6] # dump coordinates
              waiting_point: [8.59 31.37 -1.598] # x, y, yaw
#              position: [-0.65, -0.055]
#              waiting_point: [2.98 0.31 -3.09]
              floor: 1
              height: 3.0
